name: Release and deploy Todo

on:
  push:
    branches:
    - "release/*"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: branch name
    run: echo "branch name - ${{github.ref_name}}"
    - name: Checkout the branch
    uses: actions/checkout@v3
    with:
     ref: ${{github.ref_name}}